class DiffType:
    MISSING_ELEMENT = 'ELEMENT_MISSING_ON_WEBSITE_PAGE'
    EXTRA_ELEMENT   = 'EXTRA_ELEMENT_ON_WEBSITE_PAGE'
    WRONG_POSITION  = 'WRONG_POSITION_ON_WEBSITE_PAGE'
    WRONG_POSITION_WITHIN = 'WRONG_POSITION_WITHIN_CONTAINER'
    WRONG_SIZE      = 'WRONG_SIZE_ON_WEBSITE_PAGE'
    WRONG_COPY      = 'WRONG_COPY_ON_WEBSITE_PAGE' 